### ISSUE TITLE
New version of Controls.py and ControlDemo.py

### ISSUE THREAD

**Issue by pyjsorg** [pyjs/original-pyjs#352]
Added AreaSlider, which calculates position of draggable handle on a
control in a square area. 

_Original issue: http://code.google.com/p/pyjamas/issues/detail?id=367 (February 08, 2010 03:35:30)_

**Comment by pyjsorg** [comment]
_From luke.lei...@gmail.com on March 27, 2010 12:02:54:_
bill, hi, thank you for this.
note: PLEASE read and follow PEP8, and run pep8.py on future submissions
i had to do a ton of extra work to put this into the correct coding standards.

**Comment by pyjsorg** [comment]
_From luke.lei...@gmail.com on March 27, 2010 12:08:19:_
running under pyjd i get this:

Traceback (most recent call last):
  File "ControlDemo.py", line 159, in <module>
    app.onModuleLoad()
  File "ControlDemo.py", line 136, in onModuleLoad
    if start_value is None:
NameError: global name 'start_value' is not defined

_please_ test with --strict as well as -O if you are only going to run under pyjs.

**Comment by pyjsorg** [comment]
_From luke.lei...@gmail.com on March 27, 2010 12:10:23:_
ok, they're in - excellent stuff.  remember pep8.py next time :)

**Comment by pyjsorg** [comment]
_From wgwin...@gmail.com on March 27, 2010 18:29:32:_
I'm on pep8 and will test more thoroughly. (Hey! I actually did a diff! That's
progress! Though I'm soon going to owe you tutor fees. I know they are high in the UK.)
