### ISSUE TITLE
Translator.py issue -- Bug raising error

### ISSUE THREAD

**Issue by pyjsorg** [pyjs/original-pyjs#424]
<b>What steps will reproduce the problem?</b>
1. Make a browser specific version of a pyjamas app.  It doesn't matter 
what the app does.
2. Make sure that the method used in the browser-specific version does not 
exist in the general version.
3. Run it.

<b>What is the expected output? What do you see instead?</b>
I would expect to see a TraslationError raised, telling me what method 
doesn't exist.  Instead, I see a name error because self.module_name is 
used to raise the error, but used inside a function.  You just need a 
different way to get the module name.

Svn 1917

Error when compiling:

Traceback (most recent call last):  
  File &quot;/home/wiiboy/Desktop/pyjamas/bin/pyjsbuild&quot;, line 21, in &lt;module&gt;  
    pyjs.browser.build_script()  
  File &quot;/home/wiiboy/Desktop/pyjamas/pyjs/src/pyjs/browser.py&quot;, line 449, 
in build_script  
    l()  
  File &quot;/home/wiiboy/Desktop/pyjamas/pyjs/src/pyjs/linker.py&quot;, line 112, in 
**call**  
    self.visit_modules(self.modules, platform)  
  File &quot;/home/wiiboy/Desktop/pyjamas/pyjs/src/pyjs/linker.py&quot;, line 150, in 
visit_modules  
    self.visit_module(p, override_paths, platform, module_name=mn)  
  File &quot;/home/wiiboy/Desktop/pyjamas/pyjs/src/pyjs/linker.py&quot;, line 200, in 
visit_module  
    **self.translator_arguments)  
  File &quot;/home/wiiboy/Desktop/pyjamas/pyjs/src/pyjs/translator.py&quot;, line 
3619, in translate  
    tree = merge(compiler.ast, module_name, tree, current_tree, flags)  
  File &quot;/home/wiiboy/Desktop/pyjamas/pyjs/src/pyjs/translator.py&quot;, line 
3652, in merge  
    replaceClassMethods(ast, tree1, child.name, child)  
  File &quot;/home/wiiboy/Desktop/pyjamas/pyjs/src/pyjs/translator.py&quot;, line 
3703, in replaceClassMethods  
    node, self.module_name)  
NameError: global name 'self' is not defined

_Original issue: http://code.google.com/p/pyjamas/issues/detail?id=295 (September 29, 2009 02:38:43)_

**Comment by pyjsorg** [comment]
_From jordonwii on September 29, 2009 02:40:04:_
I modified translator.py, and used the word "Blob" in place of self.module_name.  The 
error, in my instance, should be something like:
Traceback (most recent call last):
  File "/home/wiiboy/Desktop/pyjamas/bin/pyjsbuild", line 21, in <module>
    pyjs.browser.build_script()
  File "/home/wiiboy/Desktop/pyjamas/pyjs/src/pyjs/browser.py", line 449, in 
build_script
    l()
  File "/home/wiiboy/Desktop/pyjamas/pyjs/src/pyjs/linker.py", line 116, in **call**
    raise e
pyjs.translator.TranslationError/home/wiiboy/Desktop/pyjamas/pyjs/src/pyjs/translator
.py:585: DeprecationWarning: BaseException.message has been deprecated as of Python 
2.6
  return self.message
: Blob line 6:
class method not found: Homepage.Warn
Function(None, 'Warn', ['self'], [], 0, None, Stmt([Assign([AssName('box', 
'OP_ASSIGN')], CallFunc(Name('BrowserWarning'), [], None, None)), 
Discard(CallFunc(Getattr(Name('box'), 'show'), [], None, None))]))

**Comment by pyjsorg** [comment]
_From luke.lei...@gmail.com on September 29, 2009 23:18:05:_
-            replaceFunction(ast, tree1, child.name, child)
-            replaceFunction(ast, module_name, tree1, child.name, child)
       elif isinstance(child, ast.Class):
-            replaceClassMethods(ast, tree1, child.name, child)
-            replaceClassMethods(ast, module_name, tree1, child.name, child)
       else:
           raise TranslationError(
               "Do not know how to merge %s" % child, child, module_name)
   return tree1

-def replaceFunction(ast, tree, function_name, function_node):
+def replaceFunction(ast, module_name, tree, function_name, function_node):
     # find function to replace
     for child in tree.node:
         if isinstance(child, ast.Function) and child.name == function_name:
             copyFunction(child, function_node)
             return
     raise TranslationError(
-        "function not found: " + function_name, function_node, None)
- ```
     "function not found: " + function_name, function_node, module_name)
  ```
  
  def copyFunction(target, source):
     target.code = source.code
  @@ -3674,7 +3674,7 @@ def addCode(target, source):

-def replaceClassMethods(ast, tree, class_name, class_node):
+def replaceClassMethods(ast, module_name, tree, class_name, class_node):
     # find class to replace
     old_class_node = None
     for child in tree.node:
@@ -3684,7 +3684,7 @@ def replaceClassMethods(ast, tree, class_name, class_node)

```
 if not old_class_node:
     raise TranslationError(
```
-            "class not found: " + class_name, class_node, self.module_name)
- ```
         "class not found: " + class_name, class_node, module_name)
  ```
  
   # replace methods
   for node in class_node.code:
  @@ -3699,7 +3699,7 @@ def replaceClassMethods(ast, tree, class_name, class_node)
           if not found:
               raise TranslationError(
                   "class method not found: " + class_name + "." + node.name,
-                    node, self.module_name)
-                    node, module_name)
       elif isinstance(node, ast.Assign) and \
            isinstance(node.nodes[0], ast.AssName):
           found = False

**Comment by pyjsorg** [comment]
_From luke.lei...@gmail.com on September 29, 2009 23:18:27:_
svn r1924

**Comment by pyjsorg** [comment]
_From luke.lei...@gmail.com on November 03, 2009 12:54:34:_
jordan, is that better?
can i close this bug?

**Comment by pyjsorg** [comment]
_From jordonwii on November 03, 2009 15:01:24:_
Ya.  It works.

**Comment by pyjsorg** [comment]
_From luke.lei...@gmail.com on November 09, 2009 20:08:12:_
ok good stuff.
