### ISSUE TITLE
__get__ optimisation code is bypassing checks made in getattr

### ISSUE THREAD

**Issue by pyjsorg** [pyjs/original-pyjs#453]
<b>What steps will reproduce the problem?</b>
<b>1.</b>
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>

<b>Please use labels and text to provide additional information.</b>

_Original issue: http://code.google.com/p/pyjamas/issues/detail?id=266 (September 18, 2009 13:19:31)_

**Comment by pyjsorg** [comment]
_From luke.lei...@gmail.com on September 18, 2009 13:22:49:_
this code is wrong:

```
        if self.bound_methods or self.descriptors:
            if not self.descriptors:
                getattr_condition = "typeof %(attr)s == 'function' &&
```

%(attr_left)s.**is_instance**"
                else:
                    getattr_condition = """%(attr_left)s !== null &&
%(attr_left)s.**is_instance** && 
(typeof %(attr)s == 'function')||
(%(attr_left)s['%(attr_right)s'] !== null && 
typeof %(attr_left)s['%(attr_right)s']['**get**'] == 'function')"""
                attr_code = """\
(""" + getattr_condition + """?
\tpyjslib['getattr'](%%28attr_left%29s,):
\t%(attr)s)\
"""
                attr_code = ('\n'+self.spacing()+"\t\t").join(attr_code.split('\n'))

it results in this:

```
        try {
            $pyjs.track.lineno=338;
            z = (instance !== null && instance.__is_instance__ &&
                    (typeof instance['z'] == 'function')||
                    (instance['z'] !== null &&
                    typeof instance['z']['__get__'] == 'function')?
                        pyjslib['getattr'](instance, 'z'):
                        instance['z']);
```

which is from ClassTest.testSuperTest():

```
    try:
        z = instance.z
        self.fail("failed to raise error for instance.z")
    except AttributeError, e:
        self.assertTrue(True)
```

what's happening, under pyv8, is the following error message:

ClassTest.py, line 338:
    z = instance.z
Traceback (most recent call last):
  File "pyv8run.py", line 281, in <module>
    main()
  File "pyv8run.py", line 277, in main
    x = ctxt.eval(txt)
PyV8.JSError: JSError: TypeError: Cannot read property '**get**' of undefined (  @
813 : 4 )  ->                                throw e;

what's being bypassed is the correct testing, being done in pyjslib.getattr:

```
if ((!pyjslib.isObject(obj))||(pyjslib.isUndefined(obj[name]))){
    if (arguments.length != 3){
        throw pyjslib.AttributeError(obj, name);
    }else{
    return default_value;
    }
}
var method = obj[name];
if (method !== null && typeof method.__get__ == 'function') {
    if (obj.__is_instance__) {
        return method.__get__(obj, obj.__class__);
    } else {
        return method.__get__(null, obj.__class__);
    }
}
```

**Comment by pyjsorg** [comment]
_From luke.lei...@gmail.com on September 18, 2009 13:37:55:_
i added an extra test, it seems ok

**Comment by pyjsorg** [comment]
_From luke.lei...@gmail.com on September 26, 2009 23:37:52:_
seems fine.
