### ISSUE TITLE
pyjsbuild = "invalid directory name" ?

### ISSUE THREAD

**Issue by pyjsorg** [pyjs/original-pyjs#47]
<b>Before reporting a problem, please UPDATE TO LATEST SVN.</b>
<b>As this is a community-driven project, the developers only</b>
<b>have time available to fix problems reported in the LATEST</b>
<b>code.  You are welcome to report problems in any other</b>
<b>version, but until you have upgraded to latest svn and provided</b>
<b>a test report against that, you will be reliant on people</b>
<b>OTHER than the core developers for bug-fixes.  which could</b>
<b>happen, so feel free to ignore the above should you so choose.</b>

<b>What steps will reproduce the problem?</b>
1. I just downloaded pyjamas 0.8
2. python bootstrap.py
3. pyjsbuild Hello.py # helloworld example

<b>What is the expected output? What do you see instead?</b>
- Here is what I see:
  H:\Data\helloworld&gt;pyjsbuild Hello
  Building : Hello
  PYJSPATH : [
  H:\Data\helloworld
  H:\Data#Progs\PortaPy\weitere module\pyjamas-0.8alpha1\library
  H:\Data#Progs\PortaPy\weitere module\pyjamas-0.8alpha1\addons
  ]
  Translating : H:\Data#Progs\PortaPy\weitere module\pyjamas-0.8alpha1\pyjs\src\pyjs\builtin\pyjslib.py
  Traceback (most recent call last):
  File &quot;H:\Data#Progs\PortaPy\weitere module\pyjamas-0.8alpha1\bin\pyjsbuild.py&quot;, line 21, in &lt;module&gt;
    pyjs.browser.build_script()
  File &quot;H:\Data#Progs\PortaPy\weitere module\pyjamas-0.8alpha1\pyjs\src\pyjs\browser.py&quot;, line 542, in build_script
    runtime_options, args)
  File &quot;H:\Data#Progs\PortaPy\weitere module\pyjamas-0.8alpha1\pyjs\src\pyjs\browser.py&quot;, line 395, in build
    l()
  File &quot;H:\Data#Progs\PortaPy\weitere module\pyjamas-0.8alpha1\pyjs\src\pyjs\linker.py&quot;, line 228, in **call**
    self.visit_modules(['pyjslib'], platform)
  File &quot;H:\Data#Progs\PortaPy\weitere module\pyjamas-0.8alpha1\pyjs\src\pyjs\linker.py&quot;, line 282, in visit_modules
    self.visit_module(p, override_paths, platform, module_name=mn)
  File &quot;H:\Data#Progs\PortaPy\weitere module\pyjamas-0.8alpha1\pyjs\src\pyjs\linker.py&quot;, line 335, in visit_module
    self.keep_lib_files)
  File &quot;H:\Data#Progs\PortaPy\weitere module\pyjamas-0.8alpha1\pyjs\src\pyjs\linker.py&quot;, line 119, in out_translate
    env=os.environ
  File &quot;H:\Data#Progs\PortaPy\PortablePython 2.7.2.1\Portable Python 2.7.2.1\App\lib\subprocess.py&quot;, line 679, in **init**
    errread, errwrite)
  File &quot;H:\Data#Progs\PortaPy\PortablePython 2.7.2.1\Portable Python 2.7.2.1\App\lib\subprocess.py&quot;, line 893, in _execute_child
    startupinfo)
  WindowsError: [Error 267] Der Verzeichnisname ist ungⁿltig

Last thing is German and means: directory name is not valid. Maybe because of space character or character &quot;#&quot; ?!

<b>What version of Pyjamas are you using?  which svn revision number?</b>
<b>On what operating system?</b>
- pyjamas-0.8alpha1 on Python 2.7.2.1 on Win7

_Original issue: http://code.google.com/p/pyjamas/issues/detail?id=676 (January 09, 2012 17:34:27)_

**Comment by pyjsorg** [comment]
_From cesare.d...@gmail.com on March 28, 2012 12:43:20:_
The same applies to a project with a path having spaces inside:

C:\Temp\Pyjamas\Slideshow Basic>pyjsbuild.bat --print-statements Slideshow.py
Building : Slideshow
PYJSPATH : [
    C:\Temp\Pyjamas\Slideshow Basic
    d:\Dropbox\pyjamas\v8\library
    d:\Dropbox\pyjamas\v8\addons
]
Translating : C:\Temp\Pyjamas\Slideshow Basic\Slideshow.py
Traceback (most recent call last):
  File "d:\Dropbox\pyjamas\v8\bin\pyjsbuild.py", line 21, in <module>
    pyjs.browser.build_script()
  File "d:\Dropbox\pyjamas\v8\pyjs\src\pyjs\browser.py", line 542, in build_script
    runtime_options, args)
  File "d:\Dropbox\pyjamas\v8\pyjs\src\pyjs\browser.py", line 395, in build
    l()
  File "d:\Dropbox\pyjamas\v8\pyjs\src\pyjs\linker.py", line 230, in **call**
    self.visit_modules(self.modules, platform)
  File "d:\Dropbox\pyjamas\v8\pyjs\src\pyjs\linker.py", line 282, in visit_modules
    self.visit_module(p, override_paths, platform, module_name=mn)
  File "d:\Dropbox\pyjamas\v8\pyjs\src\pyjs\linker.py", line 335, in visit_module
    self.keep_lib_files)
  File "d:\Dropbox\pyjamas\v8\pyjs\src\pyjs\linker.py", line 119, in out_translate
    env=os.environ
  File "D:\Dropbox\Python26\lib\subprocess.py", line 623, in **init**
    errread, errwrite)
  File "D:\Dropbox\Python26\lib\subprocess.py", line 833, in _execute_child
    startupinfo)
WindowsError: [Error 267] Nome di directory non valido

Windows 7 x64 / Python 2.7.2 / Python 0.8
