### ISSUE TITLE
'pip install pyjs' doesn't work

### ISSUE THREAD

**Issue by glyph** [pyjs/original-pyjs#742]
It would be nice if I could just do 'pip install' and have a working environment, but there appear to be several idiosyncratic intermediary build steps that prevent this.

**Comment by kineticz** [comment]
+1 for this!

**Comment by glyph** [comment]
(It would be nice to get rid of the 'bootstrap.py' stuff so that 'pip install' works equally well with the --user option.  Distutils already has things for identifying what directories to put things into.)

**Comment by anthonyrisinger** [comment]
yes, fixing is pip as much as possible is very close to the top of list; should be some activity here soon.

**Comment by glyph** [comment]
Great, glad to hear it.

**Comment by duly** [comment]
We look forward to `pip install pyjs`. Thank you.

**Comment by glyph** [comment]
Can you break down this task at all?  I'm happy just to do some cheerleading but if there's a small PR that I could submit which would make it easier I'm happy to try to work on the code a little.

**Comment by duly** [comment]
Helpful links:
https://pypi.python.org/pypi/pyjs
https://pypi.python.org/pypi/pip

**Comment by duly** [comment]
https://github.com/pypa/pip/issues

**Comment by duly** [comment]
https://pypi.python.org/simple/pyjs/pyjs.org/

## `HTTP Error 404: Not Found`

```
 Analyzing links from page https://pypi.python.org/simple/pyjs/
    Skipping link https://github.com/pyjs/pyjs.git (from https://pypi.python.org/simple/pyjs/); unknown archive format: .git
 Analyzing links from page https://github.com/pyjs/pyjs
    Skipping link https://github.com/pyjs/pyjs#start-of-content (from https://github.com/pyjs/pyjs); not a file
    Skipping link https://github.com/ (from https://github.com/pyjs/pyjs); not a file
...
Could not parse version from link: https://github.com/pyjs/pyjs/archive/master.zip (from https://github.com/pyjs/pyjs)
--
 Skipping link https://github.com/pyjs/pyjs/blob/master/setup.py (from https://github.com/pyjs/pyjs); unknown archive format: .py
--
 Skipping link http://pyjs.org/ (from https://github.com/pyjs/pyjs); not a file

--
```

There are a lot of concerns searching for the right file from the sampling of links that pip tries when installing pyjs.
What is the correct and official pyjs pip download link?
Thank you.
Duly Corporation

**Comment by duly** [comment]
The following link returns a weight of 9 on pypi search[1]:
https://pypi.python.org/pypi/pyjs/0.8.1-dev

[1] - https://pypi.python.org/pypi?%3Aaction=search&term=pyjs&submit=search

**Comment by duly** [comment]
`pip install -e git+https://github.com/pyjs/pyjs.git#egg=pyjs`

```
PS > pip install -e git+https://github.com/pyjs/pyjs.git#egg=pyjs
Obtaining pyjs from git+https://github.com/pyjs/pyjs.git#egg=pyjs
  Updating REDACTED\pyjs clone
  Running setup.py egg_info for package pyjs
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "REDACTED\src\pyjs\setup.py", line 7, in <module>
        package_data=dict(setup_pyjstools.package_data.items()+setup_pyjswidgets.package_data.items())
    TypeError: unsupported operand type(s) for +: 'dict_items' and 'dict_items'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "REDACTED\src\pyjs\setup.py", line 7, in <module>
    package_data=dict(setup_pyjstools.package_data.items()+setup_pyjswidgets.package_data.items())

TypeError: unsupported operand type(s) for +: 'dict_items' and 'dict_items'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in REDACTED\src\pyjs
```

We are still working through the issues with `pip install pyjs` here at Duly.

**Comment by duly** [comment]
It seems as though our error is due to Python 2to3 migration / compatibility.
http://stackoverflow.com/questions/13361510/typeerror-unsupported-operand-types-for-dict-items-and-dict-items
We will investigate a quick fix.

**Comment by duly** [comment]
We were able to install pyjs with pip with a few modifications to setup.py.
We will send a pull-request to pyjs.
There are a few files missing from pyjs that pip warns are not found.
We will add those files and send a pull-request to pyjs/pyjs.

```
PS > pip install -v -e git+https://github.com/duly/pyjs.git#egg=pyjs
Obtaining pyjs from git+https://github.com/duly/pyjs.git#egg=pyjs
  Found command 'git' at 'REDACTED\\Git\\cmd\\git.exe'
  https://github.com/duly/pyjs.git
  Clone in REDACTED\src\pyjs exists, and has correct URL (https://github.com/duly/pyjs.git)
  Updating REDACTED\src\pyjs clone
  4dd172b7469917ba64dab659d385390dd1180800 refs/heads/master
  87af7172874e6fccc2c17ce530b819553956a8a8 refs/remotes/origin/HEAD
  87af7172874e6fccc2c17ce530b819553956a8a8 refs/remotes/origin/master
  ade2da99ebe844bf2aedd004dc805c78f9d057f4 refs/tags/0.8
  07f54ad054073187634c49a49e0bb38e95766872 refs/tags/0.8.1a
  Running setup.py egg_info for package pyjs
    running egg_info
    writing pyjs.egg-info\PKG-INFO
    writing entry points to pyjs.egg-info\entry_points.txt
    writing top-level names to pyjs.egg-info\top_level.txt
    writing dependency_links to pyjs.egg-info\dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    package init file 'pyjs\lib\test\__init__.py' not found (or not a regular file)
    package init file 'pyjs\lib_trans\test\__init__.py' not found (or not a regular file)
    package init file 'pyjs\boilerplate\__init__.py' not found (or not a regular file)
    reading manifest file 'pyjs.egg-info\SOURCES.txt'
    writing manifest file 'pyjs.egg-info\SOURCES.txt'
Installing collected packages: pyjs
  Running setup.py develop for pyjs
    running develop
    running egg_info
    writing top-level names to pyjs.egg-info\top_level.txt
    writing pyjs.egg-info\PKG-INFO
    writing entry points to pyjs.egg-info\entry_points.txt
    writing dependency_links to pyjs.egg-info\dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    package init file 'pyjs\lib\test\__init__.py' not found (or not a regular file)
    package init file 'pyjs\lib_trans\test\__init__.py' not found (or not a regular file)
    package init file 'pyjs\boilerplate\__init__.py' not found (or not a regular file)
    reading manifest file 'pyjs.egg-info\SOURCES.txt'
    writing manifest file 'pyjs.egg-info\SOURCES.txt'
    running build_ext
    Creating REDACTED\python\3.3.2\lib\site-packages\pyjs.egg-link (link to .)
    Adding pyjs 0.8.2 to easy-install.pth file
    Installing pyjscompile-script.py script to REDACTED\python\3.3.2\Scripts
    Installing pyjscompile.exe script to REDACTED\python\3.3.2\Scripts
    Installing pyv8run-script.py script to REDACTED\python\3.3.2\Scripts
    Installing pyv8run.exe script to REDACTED\python\3.3.2\Scripts
    Installing java2py-script.py script to REDACTED\python\3.3.2\Scripts
    Installing java2py.exe script to REDACTED\python\3.3.2\Scripts
    Installing pyjsbuild-script.py script to REDACTED\python\3.3.2\Scripts
    Installing pyjsbuild.exe script to REDACTED\python\3.3.2\Scripts
    Installing pyjscompressor-script.py script to REDACTED\python\3.3.2\Scripts
    Installing pyjscompressor.exe script to REDACTED\python\3.3.2\Scripts
    Installing pyjstest-script.py script to REDACTED\python\3.3.2\Scripts
    Installing pyjstest.exe script to REDACTED\python\3.3.2\Scripts
    Installing pyjampiler-script.py script to REDACTED\python\3.3.2\Scripts
    Installing pyjampiler.exe script to REDACTED\python\3.3.2\Scripts
    Installing mo2json-script.py script to REDACTED\python\3.3.2\Scripts
    Installing mo2json.exe script to REDACTED\python\3.3.2\Scripts

    Installed REDACTED\src\pyjs
Successfully installed pyjs
Cleaning up...
  Removing temporary dir REDACTED\temp\pip_build_REDACTED...
```

**Comment by glyph** [comment]
In order to complete this work and close this issue, someone also needs to run `setup.py sdist upload`.  Have you experimented with setting up [Warehouse](https://pypi.python.org/pypi/warehouse) and uploading to that?  That would at least prove that uploading and sdists work well enough :-).

**Comment by glyph** [comment]
Thanks for moving this issue forward, @duly !

**Comment by duly** [comment]
We are looking into integration with warehouse. Thank you @glyph for the recommendation.

**Comment by hidewyb** [comment]
I have used user command: pip install git+https://github.com/pyjs/pyjs.git#egg=pyjs to install pyjs but it is not working. The error is as following:
![ehc3n j4_6t kfs vigv60](https://cloud.githubusercontent.com/assets/9999769/12136869/d6a1b2a8-b486-11e5-8a6c-f1885bac9197.png)

**Comment by bittner** [comment]
@hidewyb The error message says that `git` cannot be found. Make sure you have Git installed and it's in your path. Installing from a git repository requires that the repo will first be cloned, hence the git command must be available.
