### ISSUE TITLE
"make system-install" leads to missing pycompiler import

### ISSUE THREAD

**Issue by DanielKinsman** [pyjs/original-pyjs#750]
Running "make local-build" gives me bin/pyjsbuild which works fine.
Running "sudo make system-install" gives me  /usr/bin/pyjsbuild which produces the following error whenever you run it:

Traceback (most recent call last):
  File "/usr/bin/pyjsbuild", line 16, in <module>
    import pyjs.browser
  File "/usr/local/lib/python2.7/dist-packages/pyjs/browser.py", line 8, in <module>
    from pyjs import linker
  File "/usr/local/lib/python2.7/dist-packages/pyjs/linker.py", line 8, in <module>
    from pyjs import translator
  File "/usr/local/lib/python2.7/dist-packages/pyjs/translator.py", line 15, in <module>
    from translator_proto import *
  File "/usr/local/lib/python2.7/dist-packages/pyjs/translator_proto.py", line 37, in <module>
    import pycompiler as compiler
ImportError: No module named pycompiler

I'm using the current source of pyjs from github, running linux mint debian edition, xfce, amd64. Am I doing something wrong or is this a bug in pyjs?

**Comment by DanielKinsman** [comment]
Looks like this is probably related to https://github.com/pyjs/pyjs/issues/751

If I get the chance I might look into it and update the Makefile.
