### ISSUE TITLE
trouble building pyjd on ubuntu 12.04

### ISSUE THREAD

**Issue by ghost** [pyjs/original-pyjs#755]
I'm having trouble compiling pyjd on ubuntu 12.04.   I've followed the instructions on the wiki at

https://github.com/pyjs/pyjs/wiki/pyjamasubuntuwebkitgtk

and I am able to follow the instructions successfully  to the ../autogen.sh statement (and ../configure, via the call in autogen.sh) but receive the following error as configure executes:

.
.
checking for libpng... yes
checking usage of GTK+... yes
checking the GTK+ version to use... ../configure: line 18321: syntax error near unexpected token `!='
../configure: line 18321:`  withval=$with_gtk; case $with_gtkplus != "no" && "$with_gtk" in'

it looks like there is a syntax error near the expression $with_gtkplus != "no".   I believe the statement is generated by autogen.sh.  Should I try to (find and)  contact the owners of git://git.savannah.gnu.org/pythonwebkit.git ?  Or is this related to pyjs somehow?

**Comment by anthonyrisinger** [comment]
If you search the old pyjamas-dev list you'll find a post by me linking to
~5 patches that fix most -- but IIRC no longer all :-( -- of these issues.

AFAIK Luke Leighton and probably some others manage that code.

The specific error you are seeing is due to the `case` statement being
removed from the core language in Perl ... replace with if/else, import
Case, or apply my patches.

**Comment by anthonyrisinger** [comment]
apply the 6 pathes from here:

(AUR) https://aur.archlinux.org/packages.php?ID=50802
(direct) https://aur.archlinux.org/packages/py/pyjamas-engine-pythonwebkit/pyjamas-engine-pythonwebkit.tar.gz

... but there may be more problems after that.  pyjd is getting harder and harder to run, so i'll be returing to the gobject-based  binding ASAP, but i'm totally booked for one more week.

**Comment by ghost** [comment]
Thanks for the links.  So do you recommend that someone develops with pyjd
or pyjs?   If pyjd is getting harder to run, should I just stick with pyjs?

On Wed, Jul 18, 2012 at 11:28 AM, C Anthony Risinger <
reply@reply.github.com

**Comment by ghost** [comment]
I've installed the libwebkit updates via ppa,  checked out feature/giwebkit,   reran bootstrap.py and then ran run_bootstap_then_pyjd_setup.py.     But when I type the following commands I get the following errors:

~/git/pyjs/examples/asteroids$ ../../bin/pyjd Space.py 

``` python
INFO:pyjs.runners:conf: {'runner': 'pywebkitgtk', 'engine': 'pywebkitgtk', 'is_desktop': True, 'native_dnd': True}
Traceback (most recent call last):
  File "Space.py", line 16, in <module>
    import pyjd # this is dummy in pyjs.
  File "/home/earney/git/pyjs/pyjd/__init__.py", line 16, in <module>
    _manager.set_runner()
  File "/usr/local/lib/python2.7/dist-packages/pyjs-0.8.1-py2.7.egg/pyjs/runners/__init__.py", line 49, in set_runner
    __import__(impl)
ImportError: No module named pywebkitgtk
```

Any suggestions?

**Comment by ghost** [comment]
I was able to get further by modifying my ~/.pyjd/pyjdrc file:

 cat ~/.pyjd/pyjdrc

``` ini
[gui]
engine=giwebkit
```

asteroids example still fails (error below), but will try other examples to see if they work for me as well. Will keep you updated. :)

``` python
~/git/pyjs/examples/asteroids$ ../../bin/pyjd Space.py 
INFO:pyjs.runners:conf: {'runner': 'giwebkit', 'engine': 'giwebkit', 'is_desktop': True, 'native_dnd': True}
DEBUG:pyjs.runners.giwebkit:file:///home/earney/git/pyjs/examples/asteroids/public/Space.html
None file:///home/earney/git/pyjs/examples/asteroids/public/Space.html
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyjs-0.8.1-py2.7.egg/pyjs/runners/giwebkit.py", line 474, in _resource_init_cb
    content_type = m.request_headers.get_content_type()[0]
AttributeError: 'NoneType' object has no attribute 'request_headers'
DEBUG:pyjs.runners.giwebkit:sub-frame: <WebFrame object at 0xa393f04 (WebKitWebFrame at 0xa8dbec0)>
set_main_frame <pyjs.runners.giwebkit.ApplicationView object at 0xa05a88c>
DEBUG:pyjs.runners.giwebkit:getattr-w3:DOMDocument.createElement [create_element]
DEBUG:pyjs.runners.giwebkit:getattr-w3:DOMHTMLDivElement.tabIndex [tab_index]
Traceback (most recent call last):
  File "Space.py", line 388, in <module>
    c = GameCanvas(800, 600)
  File "Space.py", line 141, in __init__
    GWTCanvas.__init__(self, w, h)
  File "/home/earney/git/pyjs/library/pyjamas/Canvas/GWTCanvas.py", line 73, in __init__
    self.canvas = self.impl.createElement()
  File "/home/earney/git/pyjs/library/pyjamas/Canvas/GWTCanvasImplDefault.py", line 50, in createElement
    self.setCanvasContext(e.getContext('2d'))
  File "/usr/local/lib/python2.7/dist-packages/pyjs-0.8.1-py2.7.egg/pyjs/runners/giwebkit.py", line 326, in __call__
    return self.getattr(inst, key)
  File "/usr/local/lib/python2.7/dist-packages/pyjs-0.8.1-py2.7.egg/pyjs/runners/giwebkit.py", line 336, in getattr
    inst.__class__.__name__, key))
AttributeError: 'DOMHTMLCanvasElement' object has no attribute 'getContext'
```

**Comment by anthonyrisinger** [comment]
yeah no support for canvas right now, and for forseeable future ... not out of the question but it's not enabled at gobject-level ATM, and i havent looked into it further.

don't bother with the setuptools crap ... all that stuff was pretty broken to begin with.  i'll be fixing up soon.  i would recommend using the `bin/pyjd` tool generated by bootstrap.py (that's all i ever use ... never installed to system once)

yeah you have to change the engine :-) once this branch lands i'll be changing the default to use it instead.

**Comment by bittner** [comment]
Not related to this issue, but maybe a good idea: The Asteroids example has a new version (0.2) also having sound. The source code is available from the website of the example's author: http://rumsey.org/space/Space.html (This URL is mentioned in the example's README: https://github.com/pyjs/pyjs/tree/master/examples/asteroids, Blog entry with description of changes for version 0.2: http://rumsey.org/blog/2009/11/i-made-asteroids/)

We could "upgrade" the code to have an even more impressing example game. (The only downside of this would probably be that the example then has a slightly larger code footprint.)

**Comment by ghost** [comment]
very cool.   I'll look into this.
