### ISSUE TITLE
SyntaxError in linker.py

### ISSUE THREAD

**Issue by koolok** [pyjs/original-pyjs#858]
Hi,

I tried to install pyjs by the following command : 
sudo pip install git+https://github.com/pyjs/pyjs.git#egg=pyjs

And now when I try to run : 
pyjsbuild test.py

I got a syntax error :
`Traceback (most recent call last):
  File "/usr/local/bin/pyjsbuild", line 11, in <module>
    load_entry_point('pyjs==0.8.2', 'console_scripts', 'pyjsbuild')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/pyjs/browser.py", line 8, in <module>
    from pyjs import linker
  File "/usr/local/lib/python3.5/dist-packages/pyjs/linker.py", line 267
    except translator.TranslationError, e:
                                      ^
SyntaxError: invalid syntax
`

**Comment by jggatc** [comment]
Some advice from a pyjs user. The error you have is a python3 syntax error, which occurred with /lib/python3.5/dist-packages/pyjs/linker.py whereas my install is /lib/python2.7/site-packages/pyjs/linker.py. I believe pyjs should be installed under python2.

Uncertain why pip installed pyjs under python3. Ensure you have python2 installed on your system and try reinstalling pyjs. Or install in a virtualenv, for instance from a local pyjs git folder use:

virtualenv env
source env/bin/activate
pip install <local_git>/pyjs/
<env_root>/env/bin/pyjsbuild app.py

Install using virtualenv should work with pip install git+https://github.com/pyjs/pyjs.git#egg=pyjs as well.

**Comment by koolok** [comment]
You're right ! I forced the re-install by:

pip2 install -I git+https://github.com/pyjs/pyjs.git#egg=pyjs

Thank's :+1:

**Comment by raj-bunsha** [comment]
Please uplift the support for python 3 as most games are now built in it
