### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by bauripalash** [pyjs/original-pyjs#862]

**Comment by alysdexia** [comment]
Is that a word?

**Comment by tcs-ulli** [comment]
i have no clue whats going on with the python transpilers. 
no one seems to run out of the box after pip install
i think that is what the user is asking

for pyjs this happens to me:

pyjsbuild mycleanfile.py
Traceback (most recent call last):
  File "C:\Users\Ulrich\AppData\Local\Programs\Python\Python38-32\Scripts\pyjsbuild-script.py", line 11, in <module>
    load_entry_point('pyjs==0.8.2', 'console_scripts', 'pyjsbuild')()
  File "c:\users\ulrich\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\ulrich\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "c:\users\ulrich\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "c:\users\ulrich\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\ulrich\appdata\local\programs\python\python38-32\lib\site-packages\pyjs\browser.py", line 8, in <module>
    from pyjs import linker
  File "c:\users\ulrich\appdata\local\programs\python\python38-32\lib\site-packages\pyjs\linker.py", line 267
    except translator.TranslationError, e:
                                      ^
SyntaxError: invalid syntax

**Comment by jryzkns** [comment]
I just ran into this project and tried to run it as well, it seems like pyjsdl is written in python 2, which is why there are syntax errors. Are devs looking to migrate the project to python3 any time soon?

**Comment by aehlke** [comment]
use brython or pyscript. this is dead

**Comment by ctrueden** [comment]
I've had good luck with [Transcrypt](https://github.com/TranscryptOrg/Transcrypt), and [Pyodide](https://pyodide.org/en/latest/) is also excellent.
