### ISSUE TITLE
error while building - using python 3.9

### ISSUE THREAD

**Issue by kufupa** [pyjs/original-pyjs#869]
C:\Users\johnsmith\AppData\Local\Programs\Python\Python39\Scripts\MY SCRIPTS\Birds Apolcalypse Pra v1>pyjsbuild main.py
Traceback (most recent call last):
  File "C:\Users\johnsmith\AppData\Local\Programs\Python\Python39\Scripts\pyjsbuild-script.py", line 33, in <module>
    sys.exit(load_entry_point('pyjs==0.8.2', 'console_scripts', 'pyjsbuild')())
  File "C:\Users\johnsmith\AppData\Local\Programs\Python\Python39\Scripts\pyjsbuild-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "c:\users\johnsmith\appdata\local\programs\python\python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "c:\users\johnsmith\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\users\johnsmith\appdata\local\programs\python\python39\lib\site-packages\pyjs\browser.py", line 8, in <module>
    from pyjs import linker
  File "c:\users\johnsmith\appdata\local\programs\python\python39\lib\site-packages\pyjs\linker.py", line 267
    except translator.TranslationError, e:
                                      ^
SyntaxError: invalid syntax

**Comment by jggatc** [comment]
Refer to [issue](https://github.com/pyjs/pyjs/issues/858).

**Comment by 15921483570** [comment]
the project is written in  Py2, and unfortunately, it's almost dead.

**Comment by JawadPy** [comment]
> the project is written in Py2, and unfortunately, it's almost dead.

I was really excited to try this project out, sadly it's dead now

**Comment by aehlke** [comment]
try brython or pyscript
